services:
  db:
    image: postgres:16
    container_name: cadence_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - cadence_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: cadence_api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./api:/app/api

  
  # generator:
  #   build:
  #     context: .
  #     dockerfile: ./generator/Dockerfile

  # consumer:
  #   build:
  #     context: .
  #     dockerfile: ./consumer/Dockerfile

volumes:
  cadence_pg_data:
